export const MAX_UNPOST_TEXT_LENGTH = 1000000 // one million characters
export const MAX_POST_TEXT_LENGTH = 1000000 // one million characters
export const MAX_UNPOST_SIZE_BYTES = 500000 // 500KiB
export const MAX_POST_SIZE_BYTES = 1000000 // 1MiB
export const MAX_RAND_RANGE = 1000000000 // one billion
export const MAX_RAND_OPS = 10000 // ten thousand
export const MAX_THUMBNAIL_DIM = 128
export const ALLOWED_THREAD_DIRTINESS = 10 // number of out of order messages (not used)
export const THREAD_CONNECTION_TIMEOUT = 30000 // milliseconds to wait before reporting the thread as nonexistant